
// import {Figtree } from "next/font/google";
// import "./globals.css";
import { auth } from "@/auth.config";
import MainHeader from "@/components/MainHeader/MainHeader";
import { redirect } from "next/navigation";

// const figtree = Figtree({
//   variable: "--font-figtree",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function AuthenticatedLayout({children}: Readonly<{children: React.ReactNode}>) 
{
    const session = await auth() ;

    if(!session?.user || !session){
      redirect('/login');
    }

    return (
    <>
     <MainHeader/>
     {children}
    </>
  );
}