
// import {Figtree } from "next/font/google";
// import "./globals.css";
import { auth } from "@/auth.config";
import { redirect } from "next/navigation";
import MainHeader from "@/components/MainHeader/MainHeader";
import Sidebar from "@/components/Sidebar/Sidebar";

// const figtree = Figtree({
//   variable: "--font-figtree",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function AuthenticatedLayout({children}: Readonly<{children: React.ReactNode}>) 
{
    const session = await auth();

    if(!session?.user || !session){
      redirect('/login');
    }

    return (
    <div className={'container'}>
      <Sidebar/>
      <MainHeader/>
      <div className={'main_content'}>
        {children}
      </div>
     
    </div>
  );
}